<?php

namespace Database\Seeders;

use App\Domain\CurveFitConstant\CurveFitConstantPersistenceService;
use App\Facades\VariablesFacade;

class CurveFitConstantSeeder extends TableSeeder
{
    public function __construct(CurveFitConstantPersistenceService $curveFitConstantPersistenceService)
    {
        $this->service = $curveFitConstantPersistenceService;
        $this->data = [
            // na
            [
                'stability_class' => 'A',
                'constant' => 'a',
                'value' => 213,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'a',
                'value' => 184.5,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'a',
                'value' => 156,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'a',
                'value' => 130,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'a',
                'value' => 104,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'a',
                'value' => 86,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'a',
                'value' => 68,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'a',
                'value' => 50.5,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'a',
                'value' => 34,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'b',
                'value' => 0.894,
                'distance_operator_id' => VariablesFacade::config('distance_operators.na'),
            ],

            // <
            [
                'stability_class' => 'A',
                'constant' => 'c',
                'value' => 440.8,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'd',
                'value' => 1.941,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'f',
                'value' => 9.27,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'c',
                'value' => 273.7,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'd',
                'value' => 1.545,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'f',
                'value' => 6.285,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'c',
                'value' => 106.6,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'd',
                'value' => 1.149,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'f',
                'value' => 3.3,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'c',
                'value' => 83.8,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'd',
                'value' => 1.03,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'f',
                'value' => 1.65,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'c',
                'value' => 61,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'd',
                'value' => 0.911,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'f',
                'value' => 0,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'c',
                'value' => 47.1,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'd',
                'value' => 0.818,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'f',
                'value' => -0.85,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'c',
                'value' => 33.2,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'd',
                'value' => 0.725,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'f',
                'value' => -1.7,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'c',
                'value' => 22.8,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'd',
                'value' => 0.678,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'f',
                'value' => -1.3,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'c',
                'value' => 14.35,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'd',
                'value' => 0.74,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'f',
                'value' => -0.35,
                'distance_operator_id' => VariablesFacade::config('distance_operators.<'),
            ],

            // >
            [
                'stability_class' => 'A',
                'constant' => 'c',
                'value' => 459.7,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'd',
                'value' => 2.094,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'f',
                'value' => -9.6,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'c',
                'value' => 283.95,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'd',
                'value' => 1.596,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'f',
                'value' => -3.8,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'c',
                'value' => 108.2,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'd',
                'value' => 1.098,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'f',
                'value' => 2,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'c',
                'value' => 84.6,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'd',
                'value' => 1.0045,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'f',
                'value' => 1,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'c',
                'value' => 61,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'd',
                'value' => 0.911,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'f',
                'value' => 0,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'c',
                'value' => 52.75,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'd',
                'value' => 0.7135,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'f',
                'value' => -6.5,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'c',
                'value' => 44.5,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'd',
                'value' => 0.516,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'f',
                'value' => -13,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'c',
                'value' => 55.4,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'd',
                'value' => 0.305,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'f',
                'value' => -34,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'c',
                'value' => 62.6,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'd',
                'value' => 0.18,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'f',
                'value' => 48.6,
                'distance_operator_id' => VariablesFacade::config('distance_operators.>'),
            ],

            // =
            [
                'stability_class' => 'A',
                'constant' => 'c',
                'value' => 450.25,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'd',
                'value' => 2.0175,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'A',
                'constant' => 'f',
                'value' => -0.165,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'c',
                'value' => 278.825,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'd',
                'value' => 1.5705,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'A-B',
                'constant' => 'f',
                'value' => 1.2425,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'c',
                'value' => 107.4,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'd',
                'value' => 1.1235,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B',
                'constant' => 'f',
                'value' => 2.65,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'c',
                'value' => 84.2,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'd',
                'value' => 1.01725,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'B-C',
                'constant' => 'f',
                'value' => 1.325,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'c',
                'value' => 61,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'd',
                'value' => 0.911,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C',
                'constant' => 'f',
                'value' => 0,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'c',
                'value' => 49.925,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'd',
                'value' => 0.76575,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'C-D',
                'constant' => 'f',
                'value' => -3.675,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'c',
                'value' => 38.85,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'd',
                'value' => 0.6205,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'D',
                'constant' => 'f',
                'value' => -7.35,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'c',
                'value' => 39.1,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'd',
                'value' => 0.4915,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'E',
                'constant' => 'f',
                'value' => -17.65,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'c',
                'value' => 38.475,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'd',
                'value' => 0.46,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
            [
                'stability_class' => 'F',
                'constant' => 'f',
                'value' => 24.125,
                'distance_operator_id' => VariablesFacade::config('distance_operators.='),
            ],
        ];
    }
}
